import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
 
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export enum UploadType {
  Entry=0,
  Acknowledgement=1,
  Conversion=2
}
// [
//   "Application Details",
//   "",
//   "District :",
//   "Khurda",
//   " ",
//   "Tahasil :",
//   "Bhubaneswar",
//   "",
//   "Applica",
//   "Ɵ",
//   "on No. :",
//   "2022200211924",
//   " ",
//   "Date :",
//   " ",
//   "17/12/2022",
//   "",
//   "Applicant Name :",
//   "Sushil Dev Rout",
//   "",
//   "Father's/Husband's Name :",
//   "Shatrughan Rout",
//   "",
//   "LAND SCHEDULE",
//   "",
//   "Village Name",
//   " ",
//   "Khata No",
//   " ",
//   "Plot No",
//   " ",
//   "Area (in Acres)",
//   " ",
//   "Area (in Hectares)",
//   "",
//   "େଗାଠପଟଣା",
//   " ",
//   "683/1490",
//   " ",
//   "668",
//   " ",
//   "0.2000",
//   " ",
//   "0.0809",
//   "",
//   "N.B: Please quote the Applica",
//   "Ɵ",
//   "on No. for future correspondence.",
//   "",
//   "Firefox",
//   " ",
//   "about:blank",
//   "",
//   "1 of 1",
//   " ",
//   "17/12/2022, 18:49"
// ]